//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRIS.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BBHJInfo
    {
        public string BBHJInfoID { get; set; }
        public string RegisterInfoID { get; set; }
        public string BBHJCode { get; set; }
        public string Volunteer { get; set; }
        public System.DateTime GuideTime { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    }
}
