//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRIS.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowDetails
    {
        public string Id { get; set; }
        public string CaseId { get; set; }
        public string MesText { get; set; }
        public string ImageUrl { get; set; }
        public int IsDel { get; set; }
        public System.DateTime CreateDataTime { get; set; }
    }
}
