//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRIS.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkMan
    {
        public string LinkManID { get; set; }
        public string RegisterInfoId { get; set; }
        public string LinkManName { get; set; }
        public int Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Relationship { get; set; }
        public string IdCardNo { get; set; }
        public string Career { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string TelPhone { get; set; }
        public string QQ { get; set; }
        public string WeiXin { get; set; }
        public string Email { get; set; }
        public string OtherLink { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    }
}
