//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRIS.Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SRISDBEntities : DbContext
    {
        public SRISDBEntities()
            : base("name=SRISDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BBHJInfo> BBHJInfo { get; set; }
        public virtual DbSet<FollowDetails> FollowDetails { get; set; }
        public virtual DbSet<LinkMan> LinkMan { get; set; }
        public virtual DbSet<RegisterInfo> RegisterInfo { get; set; }
        public virtual DbSet<SRType> SRType { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
